### ISSUE TITLE
layouts

### ISSUE THREAD

**Issue by sil2** [zynth17/vitailse#113] opened 2022-09-16 14:31 UTC
How to fix layouts? They are not working at all
try to put some text, for example, DEFAULT LAYOUT into layouts/default.vue and you will see - nothing changed.

**Comment by zynth17** [comment] 2022-09-16 14:57
can you share a reproduction?

**Comment by sil2** [comment] 2022-09-16 20:34
npx degit zynth17/vitailse my-vitailse-app
cd my-vitailse-app
pnpm i
pnpm run dev

try to add something into layouts/default.vue and check for changes in the browser. nothing.

**Comment by sil2** [comment] 2022-09-16 20:38
also... your src/router.ts...
is useless.

no router passed into the app from here. 
if you add 
router.beforeEach((to, from) => {}

nothing will happen. 

your router defined in vite.config in imports section.

btw... if you know how to properly configure router.beforeEach  ,, will be great.

**Comment by zynth17** [comment] 2022-09-16 23:22
woa thats so rude bro, you not even reading the docs of unplugin vue router. im closing this since you dont event know what youre talking about.

**Closed** 2022-09-16 23:22 UTC

**Comment by Dustlayer** [comment] 2023-03-02 15:45
Just stumbled over this. So if anyone faces the same issue and still needs a fix:
Go in router.ts and swap 
```
extendedRoutes = routes;
return setupLayouts(routes);
```
for
```
extendedRoutes = setupLayouts(routes);
return extendedRoutes;
```

Though @sil2 seems right about this router not being used, hence beforeEach doesn't work here. But the router setup generates the extendedRoutes, which is then imported in main.ts.
You can add beforeEach in main.ts in the setup of ViteSSG.
For example like this:
```
export const createApp = ViteSSG(
	App,
	{ routes: extendedRoutes, history: import.meta.env.SSR ? createMemoryHistory() : createWebHistory() },
	async ctx => {
        ctx.router.beforeEach((to, from, next) => {
            console.log("Before route:");
            console.log(to);
            next();
        });
		Object.values(
			import.meta.glob<{ install: ViteSetupModule }>('./modules/*.ts', {
				eager: true,
			})
		).map(i => i.install?.(ctx));
	},
	{}
);
```
